# Generated by Django 5.2.17 on 2026-09-25 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence / SKU')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du vêtement')),
                ('garment_type', models.CharField(max_length=120, verbose_name='Type de vêtement')),
                ('origin_country', models.CharField(default='France', help_text="L'origine réelle compte pour les droits, pas le pays d'expédition.", max_length=100, verbose_name='Pays de fabrication')),
                ('accessory_materials', models.JSONField(blank=True, default=list, verbose_name='Accessoires non textiles')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vêtement',
                'verbose_name_plural': 'Vêtements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.CharField(choices=[('valide_expert', "Valide par l'experte"), ('a_verifier', 'A verifier'), ('brouillon', 'Brouillon - a confirmer'), ('faible_confiance', 'Brouillon - faible confiance')], default='brouillon', max_length=30, verbose_name='Niveau de confiance')),
                ('source', models.CharField(blank=True, max_length=300, verbose_name='Source')),
                ('last_verified', models.DateField(blank=True, null=True, verbose_name='Dernière vérification')),
                ('next_review', models.DateField(blank=True, null=True, verbose_name='Prochaine révision')),
                ('validated_by_expert', models.BooleanField(default=False, verbose_name="Validé par l'experte")),
                ('notes', models.TextField(blank=True, verbose_name='Notes / pièges pratiques')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garment_type', models.CharField(help_text='Ex : Chemisier, chemise femme/fille (tissé).', max_length=120, verbose_name='Type de vêtement')),
                ('fibre_group', models.CharField(choices=[('soie', 'Soie'), ('laine', 'Laine ou poils fins'), ('coton', 'Coton'), ('autres_vegetales', 'Autres fibres (lin, chanvre, ramie…)'), ('fibres_chimiques', 'Fibres synthétiques ou artificielles')], max_length=20, verbose_name='Fibre prédominante')),
                ('hs6', models.CharField(max_length=6, verbose_name='Code HS (6 chiffres)')),
            ],
            options={
                'verbose_name': 'Règle de classement',
                'verbose_name_plural': 'Règles de classement',
                'ordering': ['garment_type', 'fibre_group'],
                'constraints': [models.UniqueConstraint(fields=('garment_type', 'fibre_group'), name='unique_rule_per_type_group')],
            },
        ),
        migrations.CreateModel(
            name='TariffLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.CharField(choices=[('valide_expert', "Valide par l'experte"), ('a_verifier', 'A verifier'), ('brouillon', 'Brouillon - a confirmer'), ('faible_confiance', 'Brouillon - faible confiance')], default='brouillon', max_length=30, verbose_name='Niveau de confiance')),
                ('source', models.CharField(blank=True, max_length=300, verbose_name='Source')),
                ('last_verified', models.DateField(blank=True, null=True, verbose_name='Dernière vérification')),
                ('next_review', models.DateField(blank=True, null=True, verbose_name='Prochaine révision')),
                ('validated_by_expert', models.BooleanField(default=False, verbose_name="Validé par l'experte")),
                ('notes', models.TextField(blank=True, verbose_name='Notes / pièges pratiques')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jurisdiction', models.CharField(choices=[('FR', 'France / UE'), ('US', 'États-Unis'), ('CN', 'Chine')], max_length=2, verbose_name='Pays / zone')),
                ('code', models.CharField(help_text='Tel que publié, ex : 6206.30.30 (USA) ou 6206 30 00 (UE).', max_length=20, verbose_name='Code douanier')),
                ('hs6', models.CharField(db_index=True, editable=False, max_length=6, verbose_name='Code HS (6 chiffres)')),
                ('description', models.TextField(verbose_name='Description')),
                ('ad_valorem_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Fraction : 0.165 pour 16,5 %. 0 si « Free ». Vide si non renseigné.', max_digits=6, null=True, verbose_name='Droit ad valorem')),
                ('specific_duty', models.CharField(blank=True, help_text="Ex : 49,6 ¢/kg. S'ajoute au droit ad valorem (droit composé).", max_length=80, verbose_name='Droit spécifique')),
                ('condition_group', models.CharField(blank=True, choices=[('soie', 'Soie'), ('laine', 'Laine ou poils fins'), ('coton', 'Coton'), ('autres_vegetales', 'Autres fibres (lin, chanvre, ramie…)'), ('fibres_chimiques', 'Fibres synthétiques ou artificielles')], max_length=20, verbose_name='Condition : famille de fibres')),
                ('condition_fibre', models.CharField(blank=True, choices=[('coton', 'Coton'), ('soie', 'Soie'), ('laine', 'Laine'), ('cachemire', 'Cachemire'), ('alpaga', 'Alpaga'), ('mohair', 'Mohair'), ('angora', 'Angora'), ('lin', 'Lin'), ('chanvre', 'Chanvre'), ('ramie', 'Ramie'), ('viscose', 'Viscose'), ('modal', 'Modal'), ('lyocell', 'Lyocell'), ('acetate', 'Acétate'), ('cupro', 'Cupro'), ('polyester', 'Polyester'), ('polyamide', 'Polyamide'), ('acrylique', 'Acrylique'), ('elasthanne', 'Élasthanne'), ('polypropylene', 'Polypropylène')], max_length=20, verbose_name='Condition : fibre précise')),
                ('condition_min_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Ex : 36 pour « contenant 36 % ou plus de lin ».', max_digits=5, null=True, verbose_name='Condition : seuil minimum (% en poids)')),
            ],
            options={
                'verbose_name': 'Ligne tarifaire',
                'verbose_name_plural': 'Lignes tarifaires',
                'ordering': ['jurisdiction', 'code'],
                'constraints': [models.UniqueConstraint(fields=('jurisdiction', 'code'), name='unique_line_per_jurisdiction')],
            },
        ),
        migrations.CreateModel(
            name='GarmentFibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fibre', models.CharField(choices=[('coton', 'Coton'), ('soie', 'Soie'), ('laine', 'Laine'), ('cachemire', 'Cachemire'), ('alpaga', 'Alpaga'), ('mohair', 'Mohair'), ('angora', 'Angora'), ('lin', 'Lin'), ('chanvre', 'Chanvre'), ('ramie', 'Ramie'), ('viscose', 'Viscose'), ('modal', 'Modal'), ('lyocell', 'Lyocell'), ('acetate', 'Acétate'), ('cupro', 'Cupro'), ('polyester', 'Polyester'), ('polyamide', 'Polyamide'), ('acrylique', 'Acrylique'), ('elasthanne', 'Élasthanne'), ('polypropylene', 'Polypropylène')], max_length=20, verbose_name='Fibre')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% en poids')),
                ('garment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fibres', to='customs.garment')),
            ],
            options={
                'verbose_name': 'Fibre',
                'verbose_name_plural': 'Composition',
                'ordering': ['-percent', 'fibre'],
                'constraints': [models.UniqueConstraint(fields=('garment', 'fibre'), name='unique_fibre_per_garment')],
            },
        ),
        migrations.CreateModel(
            name='CodeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.CharField(choices=[('valide_expert', "Valide par l'experte"), ('a_verifier', 'A verifier'), ('brouillon', 'Brouillon - a confirmer'), ('faible_confiance', 'Brouillon - faible confiance')], default='brouillon', max_length=30, verbose_name='Niveau de confiance')),
                ('source', models.CharField(blank=True, max_length=300, verbose_name='Source')),
                ('last_verified', models.DateField(blank=True, null=True, verbose_name='Dernière vérification')),
                ('next_review', models.DateField(blank=True, null=True, verbose_name='Prochaine révision')),
                ('validated_by_expert', models.BooleanField(default=False, verbose_name="Validé par l'experte")),
                ('notes', models.TextField(blank=True, verbose_name='Notes / pièges pratiques')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition_note', models.TextField(blank=True, help_text='Ce qui départage cette ligne des autres (sexe, fibre, coupe...).', verbose_name='Critère de choix')),
                ('from_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings_out', to='customs.tariffline')),
                ('to_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings_in', to='customs.tariffline')),
            ],
            options={
                'verbose_name': 'Correspondance de codes',
                'verbose_name_plural': 'Correspondances de codes',
                'constraints': [models.UniqueConstraint(fields=('from_line', 'to_line'), name='unique_mapping_pair')],
            },
        ),
    ]
