# Generated by Django 5.2.17 on 2026-09-25 16:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarmentQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(choices=[('US', 'États-Unis'), ('CN', 'Chine')], max_length=2, verbose_name='Pays destinataire')),
                ('duty_rate', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Taux de droits')),
                ('all_in_minimum_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Droit total minimum tout compris')),
                ('vat_rate', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name="TVA à l'import")),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name="Prix unitaire d'achat")),
                ('freight_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Transport international + assurance')),
                ('other_costs_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Autres frais')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('garment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='customs.garment')),
                ('tariff_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customs.tariffline', verbose_name='Ligne tarifaire utilisée')),
            ],
            options={
                'verbose_name': "Devis de coût d'arrivée",
                'verbose_name_plural': "Devis de coût d'arrivée",
                'ordering': ['-created_at'],
            },
        ),
    ]
