# Generated by Django 5.2.17 on 2026-09-02 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TariffCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Electronique grand public - Enceinte Bluetooth', max_length=200, verbose_name='Categorie')),
                ('hs_code', models.CharField(blank=True, max_length=20, verbose_name='Code HS')),
                ('origin_country', models.CharField(default='Chine', max_length=100, verbose_name="Pays d'origine")),
                ('mfn_base_rate', models.DecimalField(decimal_places=4, default=0, help_text='Fraction, ex: 0.045 pour 4.5%', max_digits=6, verbose_name='Taux MFN de base')),
                ('section_301_rate', models.DecimalField(decimal_places=4, default=0, help_text='Fraction, ex: 0.075 pour 7.5%', max_digits=6, verbose_name='Taux Section 301')),
                ('additional_surtax_rate', models.DecimalField(decimal_places=4, default=0, help_text="Ex: surtaxe 'forced labor' en vigueur depuis le 24/07/2026 (~0.125). A revalider regulierement.", max_digits=6, verbose_name='Surtaxe additionnelle')),
                ('confidence', models.CharField(choices=[('valide_expert', "Valide par l'experte"), ('a_verifier', 'A verifier'), ('brouillon', 'Brouillon - a confirmer'), ('faible_confiance', 'Brouillon - faible confiance')], default='brouillon', max_length=30, verbose_name='Niveau de confiance')),
                ('notes', models.TextField(blank=True, verbose_name='Pieges / notes pratiques')),
                ('source', models.CharField(blank=True, max_length=300, verbose_name='Source')),
                ('last_verified', models.DateField(blank=True, null=True, verbose_name='Derniere verification')),
                ('next_review', models.DateField(blank=True, null=True, verbose_name='Prochaine revision')),
                ('validated_by_expert', models.BooleanField(default=False, verbose_name="Valide par l'experte")),
                ('expert_comments', models.TextField(blank=True, verbose_name="Commentaires de l'experte")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categorie tarifaire',
                'verbose_name_plural': 'Matrice tarifaire',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=200, verbose_name='Nom du produit')),
                ('fob_unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix fournisseur (FOB) / unite')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantite')),
                ('freight_cost_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cout freight total')),
                ('amazon_referral_pct', models.DecimalField(decimal_places=4, default=0.15, help_text='Fraction, ex: 0.15 pour 15%', max_digits=6, verbose_name='Commission Amazon (referral)')),
                ('amazon_fba_fee_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais FBA / unite')),
                ('target_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix de vente cible / unite')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculations', to='calculator.tariffcategory', verbose_name='Categorie tarifaire')),
            ],
            options={
                'verbose_name': 'Calcul',
                'verbose_name_plural': 'Historique des calculs',
                'ordering': ['-created_at'],
            },
        ),
    ]
